from django.shortcuts import render
from django.http import HttpResponse  # <-- import HttpResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from . import models as book_model
from . import serializers as book_serializer
from django.db.models import Subquery,Avg,Max,Min,OuterRef,Count,Case,When,CharField,IntegerField,Sum,Exists,Q,F,Expression,ExpressionWrapper,DecimalField,Value
from django.db.models.functions import Coalesce
from django.utils import timezone
from datetime import datetime,timedelta,date

class BookListAPI(APIView):
    def get(self,request):
        pass

def hello_world(request):
    return HttpResponse('hello world')

class BookListV2API(APIView):
    # Get all books with price less than 500.
    book_with_lt_500 = book_model.Book.objects.filter(price__lt=500)
    
    # Get all books whose name contains the word "Django".
    books_whose_contains_django = book_model.Book.objects.filter(name__icontains='Django')
    
    # Fetch all authors ordered alphabetically by name.
    authors_alphabetically = book_model.Author.objects.all().order_by('name')
    
    # Get all categories whose name starts with "Sci".
    categories_start_with_sci = book_model.Category.objects.filter(name__startswith='Sci')
    
    # Find all publishers located at a specific address.
    publishers = book_model.Publisher.objects.filter(address='India')
    
    # Get all books belonging to a category named "Technology".
    books_with_technology_category = book_model.Book.objects.filter(category__name='Technology')
    
    # Fetch all books published by "Penguin".
    books_by_penguin = book_model.Book.objects.filter(author_name = 'Penguin')
    
    # Get all books where category is NULL.
    books_with_null_category = book_model.Book.objects.filter(category__isnull=True)
    
    # Fetch all sales related to a specific book.
    books_with_sales_data = book_model.Book.objects.prefetch_related('sales').get(id=1)
    
    # Get all reviews for a book with name "Clean Code".
    reviews_of_clean_code = book_model.Review.objects.filter(book__name = 'Clean Code')
    
    # Get all books written by an author named "Robert Martin".
    authors_books = book_model.Book.objects.filter(author__name='Robert Martin').distinct()
    
    # Fetch all authors of a specific book.
    authors_for_specific_book = book_model.Book.objects.prefetch_related('author').get(id=1)
    
    # Get all books that have a tag named "Bestseller".
    books_with_bestseller_tag = book_model.Book.objects.filter(tags__name='Bestseller')
    
    # Fetch all tags associated with a given book.
    tags_for_book = book_model.Tag.objects.filter(book__id=1)
    
    # Find all books that have no authors assigned.
    
    books_with_no_authors = book_model.Book.objects.filter(author__isnull=True)
    
    # Calculate the average rating of each book.
    books_with_avg_ratings = book_model.Book.objects.annotate(avg_rating = Coalesce(Avg('reviews__rating'),0))
    
    # Get the total quantity sold for each book.
    books_with_sold_quantity = book_model.Book.objects.annotate(quantity_sold=Coalesce(Sum('sales__quantity_sold'),0))
    
    # Find the total revenue generated by each book.
    
    total_revenue_by_each_book = book_model.Book.objects.annotate(revenue=Coalesce(Sum('sales__total_price'),0))
    
    # Get the number of reviews for each book.
    no_review_for_each_book = book_model.Book.objects.annotate(no_of_reviews = Coalesce(Count('reviews')))
    
    # Find the highest priced book in each category.
    books_subquery = book_model.Book.objects.filter(category = OuterRef('pk')).order_by('-price').values('price')[:1]
    
    category = book_model.Category.objects.annotate(highest_price = Subquery(books_subquery))
    
    # Fetch all sales that happened in the last 30 days.
    last_30th_date = timezone.now().date() - timedelta(days=30)
    sales_in_last_30_days = book_model.Sale.objects.filter(sale_date__gte = last_30th_date)
    
    # Get total sales per day.
    total_sales_per_day = book_model.Sale.objects.values('sale_date').annotate(total_sale = Coalesce(Sum('quantity_sold'),0))
    
    # Find books that have never been sold.
    
    sales_subquery = book_model.Sale.objects.filter(book = OuterRef('pk'))
    
    never_sold_books = book_model.Book.objects.annotate(
        has_been_sold = Exists(sales_subquery)
    ).filter(has_been_sold=False)
    
    # Get all books that were sold on a specific date.
    book_sold_on_specific_date = book_model.Book.objects.filter(sales__sale_date=date(2026,1,5))
    
    # Fetch monthly sales totals.  
    monthly_sales_total = book_model.Sale.objects.values('sale_date__year','sale_date__month').annotate(total_sales=Coalesce(Sum('quantity_sold'),0))
      
    # Optimize a query to fetch books along with their category and publisher.
    books_with_category_and_supplier = book_model.Book.objects.select_related('category','publisher')
    
    # Optimize fetching books with their authors and tags.
    books_with_authors_and_tags = book_model.Book.objects.prefetch_related('author','tags')
    
    # Fetch all categories and their related books efficiently.
    category_and_books = book_model.Category.objects.all().prefetch_related('book_set')
    
    # Fetch all books along with their reviews efficiently.
    books_with_reviews = book_model.Book.objects.prefetch_related('reviews')
    
    # Explain which relationships require select_related and which require prefetch_related in this schema.
    
    books = book_model.Book.objects.select_related('category','publisher').prefetch_related('reviews','author','tags')
    
    # Fetch books priced below 500 or belonging to category "Programming".
    books = book_model.Book.objects.filter(Q(price_lte=500)|Q(category__name='Programming'))
    
    # Get books written by "Author A" and tagged as "Popular"
    books = book_model.Book.objects.filter(Q(author__name="Author A") & Q(tags__name='Popular'))
    
    # Fetch books with price between 300 and 700.
    
    books = book_model.Book.objects.filter(price__gte=300,price__lte=700)
    
    # Find books that have either no publisher or no category.
    books = book_model.Book.objects.filter(Q(publisher__isnull=True)|Q(category__isnull=True))
    
    # Fetch books with rating greater than 4 and more than 10 reviews.
    books = book_model.Book.objects.filter(reviews__rating__gte=4).annotate(review_count = Coalesce(Count('reviews'),0)).filter(review_count__gte=10)
    
    # Get books that have at least one sale.
    sales_subquery = book_model.Sale.objects.filter(book=OuterRef('pk'))
    
    books = book_model.Book.objects.annotate(sales = Exists(sales_subquery)).filter(sales=True)
    
    # Fetch books that have no reviews.
    review_subquery = book_model.Review.objects.filter(book=OuterRef('pk'))
    books = book_model.Book.objects.annotate(has_review = Exists(review_subquery)).filter(has_review=False)
    
    # Find authors who have written at least one book.
    books_subquery = book_model.Book.objects.filter(author=OuterRef('pk'))

    authors = book_model.Author.objects.annotate(has_book=Exists(books_subquery)).filter(has_book=True)
    
    # Get publishers whose books have generated sales.
    
    sales_subquery = book_model.Sale.objects.filter(book=OuterRef('pk'))
    books_sub_query = book_model.Book.objects.annotate(has_sale = Exists(sales_subquery)).filter(has_sale=True,publisher = OuterRef('pk'))
    
    publishers = book_model.Publisher.objects.annotate(has_book_sale=Exists(books_sub_query)).filter(has_book_sale=True)
    
    # Fetch books whose total sales exceed 10,000.
    
    books = book_model.Book.objects.annotate(sales_amount=Coalesce(Sum('sales__total_price'),0)).filter(sales_amount__gte=10000)
    
    # Annotate books with their discount percentage.
    books = book_model.Book.objects.annotate(
        discount_percentage=Case(
            When(
                price__gt=0,
                then=ExpressionWrapper(
                    (F('discount')*100)/F('price'),
                    output_field=DecimalField(decimal_places=2,max_digits=5)
                )
            ),
            default=Value(0),
            output_field=DecimalField(decimal_places=2,max_digits=5)
        )
        )
    
    # Annotate books with their final price after discount.
    
    books = book_model.Book.objects.annotate(
        final_price = Case(
            When(
                price__gt=0,
                then=ExpressionWrapper(
                    F('price')-F('discount'),
                    output_field=DecimalField(max_digits=5,decimal_places=2)
                )
            ),
            default=Value(0),
            output_field=DecimalField(max_digits=5,decimal_places=2)
        )
    )
    
    # Rank books by total revenue.
    
    books = book_model.Book.objects.annotate(
        total_revenue=Coalesce(
            Sum('sales__total_price'),0
        )
    ).order_by('-total_revenue')

    # Annotate categories with number of books in them.
    categories = book_model.Category.objects.annotate(books = Coalesce(Count('book'),0)).order_by('-books')
    
    # Annotate authors with total books written.    
    authors =  book_model.Author.objects.annotate(books = Coalesce(Count('book',distinct=True),0)).order_by('-books')
    
    
    